@startuml
participant Client
autonumber
create ConcreteProductBuilder
Client -[#red]> ConcreteProductBuilder:new
participant Director
create Product
ConcreteProductBuilder -[#red]> Product: new
create Director
Client -[#red]> Director: new(concreteProductBuilder)
Client -[#red]> Director: construct()
Director -[#red]> ConcreteProductBuilder: buildPartA()
ConcreteProductBuilder -[#red]> Product: setPartA()
alt need partB
Director -[#red]> ConcreteProductBuilder: buildPartB()
ConcreteProductBuilder -[#red]> Product: setPartB()
|||
end
Director -[#red]> ConcreteProductBuilder: buildPartC()
ConcreteProductBuilder -[#red]> Product: setPartC()
Director <[#blue]-- ConcreteProductBuilder: getResult() return Product
Client <[#blue]-- Director: return Product

@enduml